CREATE USER DEVELOPER_AWR
  IDENTIFIED BY &password;

-- 1 Tablespace Quota for DEVELOPER_AWR 
-- ALTER USER DEVELOPER_AWR QUOTA UNLIMITED ON TOOLS;

-- 5 Roles for DEVELOPER_AWR 
GRANT CONNECT                  TO DEVELOPER_AWR;
GRANT SELECT_CATALOG_ROLE      TO DEVELOPER_AWR;
GRANT OEM_ADVISOR              TO DEVELOPER_AWR;
GRANT OEM_MONITOR              TO DEVELOPER_AWR;
GRANT GATHER_SYSTEM_STATISTICS TO DEVELOPER_AWR;
ALTER USER DEVELOPER_AWR DEFAULT ROLE ALL;

-- 14 System Privileges for DEVELOPER_AWR 
GRANT SELECT ANY DICTIONARY TO DEVELOPER_AWR;
GRANT ANALYZE ANY TO DEVELOPER_AWR;
GRANT ADMINISTER SQL MANAGEMENT OBJECT TO DEVELOPER_AWR;
GRANT ALTER ANY SQL PROFILE TO DEVELOPER_AWR;
GRANT DROP ANY SQL PROFILE TO DEVELOPER_AWR;
GRANT ADVISOR TO DEVELOPER_AWR;
GRANT CREATE ANY JOB TO DEVELOPER_AWR;
GRANT RESTRICTED SESSION TO DEVELOPER_AWR;
GRANT ADMINISTER ANY SQL TUNING SET TO DEVELOPER_AWR;
GRANT ADMINISTER SQL TUNING SET TO DEVELOPER_AWR;
GRANT CREATE PROCEDURE TO DEVELOPER_AWR;
GRANT SELECT ANY TABLE TO DEVELOPER_AWR;
GRANT CREATE ANY SQL PROFILE TO DEVELOPER_AWR;
GRANT CREATE TABLE TO DEVELOPER_AWR;

-- Object Privileges for DEVELOPER_AWR 
GRANT SELECT  ON SYS.DBA_HIST_SNAPSHOT TO DEVELOPER_AWR;
GRANT EXECUTE ON SYS.DBMS_AUTO_SQLTUNE TO DEVELOPER_AWR;
GRANT EXECUTE ON SYS.DBMS_LOCK TO DEVELOPER_AWR;
GRANT EXECUTE ON SYS.DBMS_MONITOR TO DEVELOPER_AWR;
GRANT EXECUTE ON SYS.DBMS_RESULT_CACHE TO DEVELOPER_AWR;
GRANT EXECUTE ON SYS.DBMS_SHARED_POOL TO DEVELOPER_AWR;
GRANT EXECUTE ON SYS.DBMS_SQLPA TO DEVELOPER_AWR;
GRANT EXECUTE ON SYS.DBMS_WORKLOAD_REPOSITORY TO DEVELOPER_AWR;
GRANT EXECUTE ON SYS.DEBUG_VERSION_RPT TO DEVELOPER_AWR;
GRANT SELECT  ON SYS.H$PSEUDO_CURSOR TO DEVELOPER_AWR;
GRANT EXECUTE ON SYS.VERSION_RPT TO DEVELOPER_AWR;
GRANT SELECT ON SYS.VX$BH TO DEVELOPER_AWR;
GRANT SELECT ON SYS.VX$K2GTE2 TO DEVELOPER_AWR;
GRANT SELECT ON SYS.VX$KGLCURSOR TO DEVELOPER_AWR;
GRANT SELECT ON SYS.VX$KGLLK TO DEVELOPER_AWR;
GRANT SELECT ON SYS.VX$KGLOB TO DEVELOPER_AWR;
GRANT SELECT ON SYS.VX$KGLPN TO DEVELOPER_AWR;
GRANT SELECT ON SYS.VX$KSLLD TO DEVELOPER_AWR;
GRANT SELECT ON SYS.VX$KSLLTR_CHILDREN TO DEVELOPER_AWR;
GRANT SELECT ON SYS.VX$KSLLTR_PARENT TO DEVELOPER_AWR;
GRANT SELECT ON SYS.VX$KSLLW TO DEVELOPER_AWR;
GRANT SELECT ON SYS.VX$KSMHP TO DEVELOPER_AWR;
GRANT SELECT ON SYS.VX$KSPPCV TO DEVELOPER_AWR;
GRANT SELECT ON SYS.VX$KSPPI TO DEVELOPER_AWR;
GRANT SELECT ON SYS.VX$KSPVLD_VALUES TO DEVELOPER_AWR;
GRANT SELECT ON SYS.VX$KSUPR TO DEVELOPER_AWR;
GRANT SELECT ON SYS.VX$KSUPRLAT TO DEVELOPER_AWR;
GRANT SELECT ON SYS.VX$KSUSE TO DEVELOPER_AWR;
GRANT SELECT ON SYS.VX$KTCXB TO DEVELOPER_AWR;
GRANT SELECT ON SYS.V_$PROCESS TO DEVELOPER_AWR;
GRANT SELECT ON SYS.V_$SESSION TO DEVELOPER_AWR;
