set echo off;
prompt *******************************************************************************************
prompt *** Creating a role for performance tuning and troubleshooting.
prompt *   using standard roles and requires creating v$ views for several fixed tables (x$).
prompt *******************************************************************************************

accept rname prompt "Role name: ";

set echo on feed on ver off;

create role &rname;

-- * Roles for the perf role:
GRANT CONNECT                  TO &rname;
GRANT SELECT_CATALOG_ROLE      TO &rname;
GRANT OEM_ADVISOR              TO &rname;
GRANT OEM_MONITOR              TO &rname;
GRANT GATHER_SYSTEM_STATISTICS TO &rname;
-- Excluded DBA role for some reasons...
--GRANT DBA                      TO &rname;
GRANT EXECUTE_CATALOG_ROLE      TO &rname;
GRANT WM_ADMIN_ROLE             TO &rname;
GRANT OPTIMIZER_PROCESSING_RATE TO &rname;
GRANT JAVA_ADMIN                TO &rname;
GRANT CAPTURE_ADMIN             TO &rname;
GRANT SCHEDULER_ADMIN           TO &rname;
GRANT EM_EXPRESS_ALL            TO &rname;


-- * System Privileges for the perf role:
grant ADMINISTER ANY SQL TUNING SET      to &rname;
grant ADMINISTER DATABASE TRIGGER        to &rname;
grant ADMINISTER RESOURCE MANAGER        to &rname;
grant ADMINISTER SQL MANAGEMENT OBJECT   to &rname;
grant ADMINISTER SQL TUNING SET          to &rname;
grant ADVISOR                            to &rname;
grant ALTER ANY ANALYTIC VIEW            to &rname;
grant ALTER ANY ASSEMBLY                 to &rname;
grant ALTER ANY ATTRIBUTE DIMENSION      to &rname;
grant ALTER ANY CLUSTER                  to &rname;
grant ALTER ANY CUBE                     to &rname;
grant ALTER ANY CUBE BUILD PROCESS       to &rname;
grant ALTER ANY CUBE DIMENSION           to &rname;
grant ALTER ANY DIMENSION                to &rname;
grant ALTER ANY EDITION                  to &rname;
grant ALTER ANY EVALUATION CONTEXT       to &rname;
grant ALTER ANY HIERARCHY                to &rname;
grant ALTER ANY INDEX                    to &rname;
grant ALTER ANY INDEXTYPE                to &rname;
grant ALTER ANY LIBRARY                  to &rname;
grant ALTER ANY MATERIALIZED VIEW        to &rname;
grant ALTER ANY MEASURE FOLDER           to &rname;
grant ALTER ANY MINING MODEL             to &rname;
grant ALTER ANY OPERATOR                 to &rname;
grant ALTER ANY OUTLINE                  to &rname;
grant ALTER ANY PROCEDURE                to &rname;
grant ALTER ANY ROLE                     to &rname;
grant ALTER ANY RULE                     to &rname;
grant ALTER ANY RULE SET                 to &rname;
grant ALTER ANY SEQUENCE                 to &rname;
grant ALTER ANY SQL PROFILE              to &rname;
grant ALTER ANY SQL TRANSLATION PROFILE  to &rname;
grant ALTER ANY TABLE                    to &rname;
grant ALTER ANY TRIGGER                  to &rname;
grant ALTER ANY TYPE                     to &rname;
grant ALTER DATABASE                     to &rname;
grant ALTER LOCKDOWN PROFILE             to &rname;
grant ALTER PROFILE                      to &rname;
grant ALTER RESOURCE COST                to &rname;
grant ALTER ROLLBACK SEGMENT             to &rname;
grant ALTER SESSION                      to &rname;
grant ALTER SYSTEM                       to &rname;
grant ALTER TABLESPACE                   to &rname;
grant ALTER USER                         to &rname;
grant ANALYZE ANY                        to &rname;
grant ANALYZE ANY DICTIONARY             to &rname;
grant AUDIT ANY                          to &rname;
grant AUDIT SYSTEM                       to &rname;
grant BACKUP ANY TABLE                   to &rname;
grant BECOME USER                        to &rname;
grant CHANGE NOTIFICATION                to &rname;
grant COMMENT ANY MINING MODEL           to &rname;
grant COMMENT ANY TABLE                  to &rname;
grant CREATE ANALYTIC VIEW               to &rname;
grant CREATE ANY ANALYTIC VIEW           to &rname;
grant CREATE ANY ASSEMBLY                to &rname;
grant CREATE ANY ATTRIBUTE DIMENSION     to &rname;
grant CREATE ANY CLUSTER                 to &rname;
grant CREATE ANY CONTEXT                 to &rname;
grant CREATE ANY CREDENTIAL              to &rname;
grant CREATE ANY CUBE                    to &rname;
grant CREATE ANY CUBE BUILD PROCESS      to &rname;
grant CREATE ANY CUBE DIMENSION          to &rname;
grant CREATE ANY DIMENSION               to &rname;
grant CREATE ANY DIRECTORY               to &rname;
grant CREATE ANY EDITION                 to &rname;
grant CREATE ANY EVALUATION CONTEXT      to &rname;
grant CREATE ANY HIERARCHY               to &rname;
grant CREATE ANY INDEX                   to &rname;
grant CREATE ANY INDEXTYPE               to &rname;
grant CREATE ANY JOB                     to &rname;
grant CREATE ANY LIBRARY                 to &rname;
grant CREATE ANY MATERIALIZED VIEW       to &rname;
grant CREATE ANY MEASURE FOLDER          to &rname;
grant CREATE ANY MINING MODEL            to &rname;
grant CREATE ANY OPERATOR                to &rname;
grant CREATE ANY OUTLINE                 to &rname;
grant CREATE ANY PROCEDURE               to &rname;
grant CREATE ANY RULE                    to &rname;
grant CREATE ANY RULE SET                to &rname;
grant CREATE ANY SEQUENCE                to &rname;
grant CREATE ANY SQL PROFILE             to &rname;
grant CREATE ANY SQL TRANSLATION PROFILE to &rname;
grant CREATE ANY SYNONYM                 to &rname;
grant CREATE ANY TABLE                   to &rname;
grant CREATE ANY TRIGGER                 to &rname;
grant CREATE ANY TYPE                    to &rname;
grant CREATE ANY VIEW                    to &rname;
grant CREATE ASSEMBLY                    to &rname;
grant CREATE ATTRIBUTE DIMENSION         to &rname;
grant CREATE CLUSTER                     to &rname;
grant CREATE CREDENTIAL                  to &rname;
grant CREATE CUBE                        to &rname;
grant CREATE CUBE BUILD PROCESS          to &rname;
grant CREATE CUBE DIMENSION              to &rname;
grant CREATE DATABASE LINK               to &rname;
grant CREATE DIMENSION                   to &rname;
grant CREATE EVALUATION CONTEXT          to &rname;
grant CREATE EXTERNAL JOB                to &rname;
grant CREATE HIERARCHY                   to &rname;
grant CREATE INDEXTYPE                   to &rname;
grant CREATE JOB                         to &rname;
grant CREATE LIBRARY                     to &rname;
grant CREATE LOCKDOWN PROFILE            to &rname;
grant CREATE MATERIALIZED VIEW           to &rname;
grant CREATE MEASURE FOLDER              to &rname;
grant CREATE MINING MODEL                to &rname;
grant CREATE OPERATOR                    to &rname;
grant CREATE PLUGGABLE DATABASE          to &rname;
grant CREATE PROCEDURE                   to &rname;
grant CREATE PROFILE                     to &rname;
grant CREATE PUBLIC DATABASE LINK        to &rname;
grant CREATE PUBLIC SYNONYM              to &rname;
grant CREATE ROLE                        to &rname;
grant CREATE ROLLBACK SEGMENT            to &rname;
grant CREATE RULE                        to &rname;
grant CREATE RULE SET                    to &rname;
grant CREATE SEQUENCE                    to &rname;
grant CREATE SESSION                     to &rname;
grant CREATE SQL TRANSLATION PROFILE     to &rname;
grant CREATE SYNONYM                     to &rname;
grant CREATE TABLE                       to &rname;
grant CREATE TABLESPACE                  to &rname;
grant CREATE TRIGGER                     to &rname;
grant CREATE TYPE                        to &rname;
grant CREATE USER                        to &rname;
grant CREATE VIEW                        to &rname;
grant DEBUG ANY PROCEDURE                to &rname;
grant DEBUG CONNECT ANY                  to &rname;
grant DEBUG CONNECT SESSION              to &rname;
grant DELETE ANY CUBE DIMENSION          to &rname;
grant DELETE ANY MEASURE FOLDER          to &rname;
grant DELETE ANY TABLE                   to &rname;
grant DEQUEUE ANY QUEUE                  to &rname;
grant DROP ANY ANALYTIC VIEW             to &rname;
grant DROP ANY ASSEMBLY                  to &rname;
grant DROP ANY ATTRIBUTE DIMENSION       to &rname;
grant DROP ANY CLUSTER                   to &rname;
grant DROP ANY CONTEXT                   to &rname;
grant DROP ANY CUBE                      to &rname;
grant DROP ANY CUBE BUILD PROCESS        to &rname;
grant DROP ANY CUBE DIMENSION            to &rname;
grant DROP ANY DIMENSION                 to &rname;
grant DROP ANY DIRECTORY                 to &rname;
grant DROP ANY EDITION                   to &rname;
grant DROP ANY EVALUATION CONTEXT        to &rname;
grant DROP ANY HIERARCHY                 to &rname;
grant DROP ANY INDEX                     to &rname;
grant DROP ANY INDEXTYPE                 to &rname;
grant DROP ANY LIBRARY                   to &rname;
grant DROP ANY MATERIALIZED VIEW         to &rname;
grant DROP ANY MEASURE FOLDER            to &rname;
grant DROP ANY MINING MODEL              to &rname;
grant DROP ANY OPERATOR                  to &rname;
grant DROP ANY OUTLINE                   to &rname;
grant DROP ANY PROCEDURE                 to &rname;
grant DROP ANY ROLE                      to &rname;
grant DROP ANY RULE                      to &rname;
grant DROP ANY RULE SET                  to &rname;
grant DROP ANY SEQUENCE                  to &rname;
grant DROP ANY SQL PROFILE               to &rname;
grant DROP ANY SQL TRANSLATION PROFILE   to &rname;
grant DROP ANY SYNONYM                   to &rname;
grant DROP ANY TABLE                     to &rname;
grant DROP ANY TRIGGER                   to &rname;
grant DROP ANY TYPE                      to &rname;
grant DROP ANY VIEW                      to &rname;
grant DROP LOCKDOWN PROFILE              to &rname;
grant DROP PROFILE                       to &rname;
grant DROP PUBLIC DATABASE LINK          to &rname;
grant DROP PUBLIC SYNONYM                to &rname;
grant DROP ROLLBACK SEGMENT              to &rname;
grant DROP TABLESPACE                    to &rname;
grant DROP USER                          to &rname;
grant EM EXPRESS CONNECT                 to &rname;
grant ENQUEUE ANY QUEUE                  to &rname;
grant EXECUTE ANY ASSEMBLY               to &rname;
grant EXECUTE ANY CLASS                  to &rname;
grant EXECUTE ANY EVALUATION CONTEXT     to &rname;
grant EXECUTE ANY INDEXTYPE              to &rname;
grant EXECUTE ANY LIBRARY                to &rname;
grant EXECUTE ANY OPERATOR               to &rname;
grant EXECUTE ANY PROCEDURE              to &rname;
grant EXECUTE ANY PROGRAM                to &rname;
grant EXECUTE ANY RULE                   to &rname;
grant EXECUTE ANY RULE SET               to &rname;
grant EXECUTE ANY TYPE                   to &rname;
grant EXECUTE ASSEMBLY                   to &rname;
grant EXPORT FULL DATABASE               to &rname;
grant FLASHBACK ANY TABLE                to &rname;
grant FLASHBACK ARCHIVE ADMINISTER       to &rname;
grant FORCE ANY TRANSACTION              to &rname;
grant FORCE TRANSACTION                  to &rname;
grant GLOBAL QUERY REWRITE               to &rname;
grant GRANT ANY OBJECT PRIVILEGE         to &rname;
grant GRANT ANY PRIVILEGE                to &rname;
grant GRANT ANY ROLE                     to &rname;
grant IMPORT FULL DATABASE               to &rname;
grant INSERT ANY CUBE DIMENSION          to &rname;
grant INSERT ANY MEASURE FOLDER          to &rname;
grant INSERT ANY TABLE                   to &rname;
grant LOCK ANY TABLE                     to &rname;
grant LOGMINING                          to &rname;
grant MANAGE ANY FILE GROUP              to &rname;
grant MANAGE ANY QUEUE                   to &rname;
grant MANAGE FILE GROUP                  to &rname;
grant MANAGE SCHEDULER                   to &rname;
grant MANAGE TABLESPACE                  to &rname;
grant MERGE ANY VIEW                     to &rname;
grant ON COMMIT REFRESH                  to &rname;
grant QUERY REWRITE                      to &rname;
grant READ ANY FILE GROUP                to &rname;
grant READ ANY TABLE                     to &rname;
grant REDEFINE ANY TABLE                 to &rname;
grant RESTRICTED SESSION                 to &rname;
grant RESUMABLE                          to &rname;
grant SELECT ANY CUBE                    to &rname;
grant SELECT ANY CUBE BUILD PROCESS      to &rname;
grant SELECT ANY CUBE DIMENSION          to &rname;
grant SELECT ANY DICTIONARY              to &rname;
grant SELECT ANY MEASURE FOLDER          to &rname;
grant SELECT ANY MINING MODEL            to &rname;
grant SELECT ANY SEQUENCE                to &rname;
grant SELECT ANY TABLE                   to &rname;
grant SELECT ANY TRANSACTION             to &rname;
grant SET CONTAINER                      to &rname;
grant UNDER ANY TABLE                    to &rname;
grant UNDER ANY TYPE                     to &rname;
grant UNDER ANY VIEW                     to &rname;
grant UPDATE ANY CUBE                    to &rname;
grant UPDATE ANY CUBE BUILD PROCESS      to &rname;
grant UPDATE ANY CUBE DIMENSION          to &rname;
grant UPDATE ANY TABLE                   to &rname;
grant USE ANY JOB RESOURCE               to &rname;
grant USE ANY SQL TRANSLATION PROFILE    to &rname;


-- Object Privileges for the perf role:
GRANT SELECT  ON SYS.DBA_HIST_SNAPSHOT          TO &rname;
GRANT EXECUTE ON SYS.DBMS_AUTO_SQLTUNE          TO &rname;
GRANT EXECUTE ON SYS.DBMS_LOCK                  TO &rname;
GRANT EXECUTE ON SYS.DBMS_MONITOR               TO &rname;
GRANT EXECUTE ON SYS.DBMS_RESULT_CACHE          TO &rname;
GRANT EXECUTE ON SYS.DBMS_SHARED_POOL           TO &rname;
GRANT EXECUTE ON SYS.DBMS_SQLPA                 TO &rname;
GRANT EXECUTE ON SYS.DBMS_WORKLOAD_REPOSITORY   TO &rname;
GRANT SELECT ON SYS.VX$BH                       TO &rname;
GRANT SELECT ON SYS.VX$K2GTE2                   TO &rname;
GRANT SELECT ON SYS.VX$KGLCURSOR                TO &rname;
GRANT SELECT ON SYS.VX$KGLLK                    TO &rname;
GRANT SELECT ON SYS.VX$KGLOB                    TO &rname;
GRANT SELECT ON SYS.VX$KGLPN                    TO &rname;
GRANT SELECT ON SYS.VX$KSLLD                    TO &rname;
GRANT SELECT ON SYS.VX$KSLLTR_CHILDREN          TO &rname;
GRANT SELECT ON SYS.VX$KSLLTR_PARENT            TO &rname;
GRANT SELECT ON SYS.VX$KSLLW                    TO &rname;
GRANT SELECT ON SYS.VX$KSMHP                    TO &rname;
GRANT SELECT ON SYS.VX$KSPPCV                   TO &rname;
GRANT SELECT ON SYS.VX$KSPPI                    TO &rname;
GRANT SELECT ON SYS.VX$KSPVLD_VALUES            TO &rname;
GRANT SELECT ON SYS.VX$KSUPR                    TO &rname;
GRANT SELECT ON SYS.VX$KSUPRLAT                 TO &rname;
GRANT SELECT ON SYS.VX$KSUSE                    TO &rname;
GRANT SELECT ON SYS.VX$KTCXB                    TO &rname;
GRANT SELECT ON SYS.V_$PROCESS                  TO &rname;
GRANT SELECT ON SYS.V_$SESSION                  TO &rname;

--GRANT EXECUTE ON SYS.DEBUG_VERSION_RPT          TO &rname;
--GRANT SELECT  ON SYS.H$PSEUDO_CURSOR            TO &rname;
--GRANT EXECUTE ON SYS.VERSION_RPT                TO &rname;

set echo off;
prompt *******************************************************************************************
prompt * Done. Role &rname has been created.
prompt *******************************************************************************************