grant ADMINISTER ANY SQL TUNING SET      to &uname;
grant ADMINISTER DATABASE TRIGGER        to &uname;
grant ADMINISTER RESOURCE MANAGER        to &uname;
grant ADMINISTER SQL MANAGEMENT OBJECT   to &uname;
grant ADMINISTER SQL TUNING SET          to &uname;
grant ADVISOR                            to &uname;
grant ALTER ANY ANALYTIC VIEW            to &uname;
grant ALTER ANY ASSEMBLY                 to &uname;
grant ALTER ANY ATTRIBUTE DIMENSION      to &uname;
grant ALTER ANY CLUSTER                  to &uname;
grant ALTER ANY CUBE                     to &uname;
grant ALTER ANY CUBE BUILD PROCESS       to &uname;
grant ALTER ANY CUBE DIMENSION           to &uname;
grant ALTER ANY DIMENSION                to &uname;
grant ALTER ANY EDITION                  to &uname;
grant ALTER ANY EVALUATION CONTEXT       to &uname;
grant ALTER ANY HIERARCHY                to &uname;
grant ALTER ANY INDEX                    to &uname;
grant ALTER ANY INDEXTYPE                to &uname;
grant ALTER ANY LIBRARY                  to &uname;
grant ALTER ANY MATERIALIZED VIEW        to &uname;
grant ALTER ANY MEASURE FOLDER           to &uname;
grant ALTER ANY MINING MODEL             to &uname;
grant ALTER ANY OPERATOR                 to &uname;
grant ALTER ANY OUTLINE                  to &uname;
grant ALTER ANY PROCEDURE                to &uname;
grant ALTER ANY ROLE                     to &uname;
grant ALTER ANY RULE                     to &uname;
grant ALTER ANY RULE SET                 to &uname;
grant ALTER ANY SEQUENCE                 to &uname;
grant ALTER ANY SQL PROFILE              to &uname;
grant ALTER ANY SQL TRANSLATION PROFILE  to &uname;
grant ALTER ANY TABLE                    to &uname;
grant ALTER ANY TRIGGER                  to &uname;
grant ALTER ANY TYPE                     to &uname;
grant ALTER DATABASE                     to &uname;
grant ALTER LOCKDOWN PROFILE             to &uname;
grant ALTER PROFILE                      to &uname;
grant ALTER RESOURCE COST                to &uname;
grant ALTER ROLLBACK SEGMENT             to &uname;
grant ALTER SESSION                      to &uname;
grant ALTER SYSTEM                       to &uname;
grant ALTER TABLESPACE                   to &uname;
grant ALTER USER                         to &uname;
grant ANALYZE ANY                        to &uname;
grant ANALYZE ANY DICTIONARY             to &uname;
grant AUDIT ANY                          to &uname;
grant AUDIT SYSTEM                       to &uname;
grant BACKUP ANY TABLE                   to &uname;
grant BECOME USER                        to &uname;
grant CHANGE NOTIFICATION                to &uname;
grant COMMENT ANY MINING MODEL           to &uname;
grant COMMENT ANY TABLE                  to &uname;
grant CREATE ANALYTIC VIEW               to &uname;
grant CREATE ANY ANALYTIC VIEW           to &uname;
grant CREATE ANY ASSEMBLY                to &uname;
grant CREATE ANY ATTRIBUTE DIMENSION     to &uname;
grant CREATE ANY CLUSTER                 to &uname;
grant CREATE ANY CONTEXT                 to &uname;
grant CREATE ANY CREDENTIAL              to &uname;
grant CREATE ANY CUBE                    to &uname;
grant CREATE ANY CUBE BUILD PROCESS      to &uname;
grant CREATE ANY CUBE DIMENSION          to &uname;
grant CREATE ANY DIMENSION               to &uname;
grant CREATE ANY DIRECTORY               to &uname;
grant CREATE ANY EDITION                 to &uname;
grant CREATE ANY EVALUATION CONTEXT      to &uname;
grant CREATE ANY HIERARCHY               to &uname;
grant CREATE ANY INDEX                   to &uname;
grant CREATE ANY INDEXTYPE               to &uname;
grant CREATE ANY JOB                     to &uname;
grant CREATE ANY LIBRARY                 to &uname;
grant CREATE ANY MATERIALIZED VIEW       to &uname;
grant CREATE ANY MEASURE FOLDER          to &uname;
grant CREATE ANY MINING MODEL            to &uname;
grant CREATE ANY OPERATOR                to &uname;
grant CREATE ANY OUTLINE                 to &uname;
grant CREATE ANY PROCEDURE               to &uname;
grant CREATE ANY RULE                    to &uname;
grant CREATE ANY RULE SET                to &uname;
grant CREATE ANY SEQUENCE                to &uname;
grant CREATE ANY SQL PROFILE             to &uname;
grant CREATE ANY SQL TRANSLATION PROFILE to &uname;
grant CREATE ANY SYNONYM                 to &uname;
grant CREATE ANY TABLE                   to &uname;
grant CREATE ANY TRIGGER                 to &uname;
grant CREATE ANY TYPE                    to &uname;
grant CREATE ANY VIEW                    to &uname;
grant CREATE ASSEMBLY                    to &uname;
grant CREATE ATTRIBUTE DIMENSION         to &uname;
grant CREATE CLUSTER                     to &uname;
grant CREATE CREDENTIAL                  to &uname;
grant CREATE CUBE                        to &uname;
grant CREATE CUBE BUILD PROCESS          to &uname;
grant CREATE CUBE DIMENSION              to &uname;
grant CREATE DATABASE LINK               to &uname;
grant CREATE DIMENSION                   to &uname;
grant CREATE EVALUATION CONTEXT          to &uname;
grant CREATE EXTERNAL JOB                to &uname;
grant CREATE HIERARCHY                   to &uname;
grant CREATE INDEXTYPE                   to &uname;
grant CREATE JOB                         to &uname;
grant CREATE LIBRARY                     to &uname;
grant CREATE LOCKDOWN PROFILE            to &uname;
grant CREATE MATERIALIZED VIEW           to &uname;
grant CREATE MEASURE FOLDER              to &uname;
grant CREATE MINING MODEL                to &uname;
grant CREATE OPERATOR                    to &uname;
grant CREATE PLUGGABLE DATABASE          to &uname;
grant CREATE PROCEDURE                   to &uname;
grant CREATE PROFILE                     to &uname;
grant CREATE PUBLIC DATABASE LINK        to &uname;
grant CREATE PUBLIC SYNONYM              to &uname;
grant CREATE ROLE                        to &uname;
grant CREATE ROLLBACK SEGMENT            to &uname;
grant CREATE RULE                        to &uname;
grant CREATE RULE SET                    to &uname;
grant CREATE SEQUENCE                    to &uname;
grant CREATE SESSION                     to &uname;
grant CREATE SQL TRANSLATION PROFILE     to &uname;
grant CREATE SYNONYM                     to &uname;
grant CREATE TABLE                       to &uname;
grant CREATE TABLESPACE                  to &uname;
grant CREATE TRIGGER                     to &uname;
grant CREATE TYPE                        to &uname;
grant CREATE USER                        to &uname;
grant CREATE VIEW                        to &uname;
grant DEBUG ANY PROCEDURE                to &uname;
grant DEBUG CONNECT ANY                  to &uname;
grant DEBUG CONNECT SESSION              to &uname;
grant DELETE ANY CUBE DIMENSION          to &uname;
grant DELETE ANY MEASURE FOLDER          to &uname;
grant DELETE ANY TABLE                   to &uname;
grant DEQUEUE ANY QUEUE                  to &uname;
grant DROP ANY ANALYTIC VIEW             to &uname;
grant DROP ANY ASSEMBLY                  to &uname;
grant DROP ANY ATTRIBUTE DIMENSION       to &uname;
grant DROP ANY CLUSTER                   to &uname;
grant DROP ANY CONTEXT                   to &uname;
grant DROP ANY CUBE                      to &uname;
grant DROP ANY CUBE BUILD PROCESS        to &uname;
grant DROP ANY CUBE DIMENSION            to &uname;
grant DROP ANY DIMENSION                 to &uname;
grant DROP ANY DIRECTORY                 to &uname;
grant DROP ANY EDITION                   to &uname;
grant DROP ANY EVALUATION CONTEXT        to &uname;
grant DROP ANY HIERARCHY                 to &uname;
grant DROP ANY INDEX                     to &uname;
grant DROP ANY INDEXTYPE                 to &uname;
grant DROP ANY LIBRARY                   to &uname;
grant DROP ANY MATERIALIZED VIEW         to &uname;
grant DROP ANY MEASURE FOLDER            to &uname;
grant DROP ANY MINING MODEL              to &uname;
grant DROP ANY OPERATOR                  to &uname;
grant DROP ANY OUTLINE                   to &uname;
grant DROP ANY PROCEDURE                 to &uname;
grant DROP ANY ROLE                      to &uname;
grant DROP ANY RULE                      to &uname;
grant DROP ANY RULE SET                  to &uname;
grant DROP ANY SEQUENCE                  to &uname;
grant DROP ANY SQL PROFILE               to &uname;
grant DROP ANY SQL TRANSLATION PROFILE   to &uname;
grant DROP ANY SYNONYM                   to &uname;
grant DROP ANY TABLE                     to &uname;
grant DROP ANY TRIGGER                   to &uname;
grant DROP ANY TYPE                      to &uname;
grant DROP ANY VIEW                      to &uname;
grant DROP LOCKDOWN PROFILE              to &uname;
grant DROP PROFILE                       to &uname;
grant DROP PUBLIC DATABASE LINK          to &uname;
grant DROP PUBLIC SYNONYM                to &uname;
grant DROP ROLLBACK SEGMENT              to &uname;
grant DROP TABLESPACE                    to &uname;
grant DROP USER                          to &uname;
grant EM EXPRESS CONNECT                 to &uname;
grant ENQUEUE ANY QUEUE                  to &uname;
grant EXECUTE ANY ASSEMBLY               to &uname;
grant EXECUTE ANY CLASS                  to &uname;
grant EXECUTE ANY EVALUATION CONTEXT     to &uname;
grant EXECUTE ANY INDEXTYPE              to &uname;
grant EXECUTE ANY LIBRARY                to &uname;
grant EXECUTE ANY OPERATOR               to &uname;
grant EXECUTE ANY PROCEDURE              to &uname;
grant EXECUTE ANY PROGRAM                to &uname;
grant EXECUTE ANY RULE                   to &uname;
grant EXECUTE ANY RULE SET               to &uname;
grant EXECUTE ANY TYPE                   to &uname;
grant EXECUTE ASSEMBLY                   to &uname;
grant EXPORT FULL DATABASE               to &uname;
grant FLASHBACK ANY TABLE                to &uname;
grant FLASHBACK ARCHIVE ADMINISTER       to &uname;
grant FORCE ANY TRANSACTION              to &uname;
grant FORCE TRANSACTION                  to &uname;
grant GLOBAL QUERY REWRITE               to &uname;
grant GRANT ANY OBJECT PRIVILEGE         to &uname;
grant GRANT ANY PRIVILEGE                to &uname;
grant GRANT ANY ROLE                     to &uname;
grant IMPORT FULL DATABASE               to &uname;
grant INSERT ANY CUBE DIMENSION          to &uname;
grant INSERT ANY MEASURE FOLDER          to &uname;
grant INSERT ANY TABLE                   to &uname;
grant LOCK ANY TABLE                     to &uname;
grant LOGMINING                          to &uname;
grant MANAGE ANY FILE GROUP              to &uname;
grant MANAGE ANY QUEUE                   to &uname;
grant MANAGE FILE GROUP                  to &uname;
grant MANAGE SCHEDULER                   to &uname;
grant MANAGE TABLESPACE                  to &uname;
grant MERGE ANY VIEW                     to &uname;
grant ON COMMIT REFRESH                  to &uname;
grant QUERY REWRITE                      to &uname;
grant READ ANY FILE GROUP                to &uname;
grant READ ANY TABLE                     to &uname;
grant REDEFINE ANY TABLE                 to &uname;
grant RESTRICTED SESSION                 to &uname;
grant RESUMABLE                          to &uname;
grant SELECT ANY CUBE                    to &uname;
grant SELECT ANY CUBE BUILD PROCESS      to &uname;
grant SELECT ANY CUBE DIMENSION          to &uname;
grant SELECT ANY DICTIONARY              to &uname;
grant SELECT ANY MEASURE FOLDER          to &uname;
grant SELECT ANY MINING MODEL            to &uname;
grant SELECT ANY SEQUENCE                to &uname;
grant SELECT ANY TABLE                   to &uname;
grant SELECT ANY TRANSACTION             to &uname;
grant SET CONTAINER                      to &uname;
grant UNDER ANY TABLE                    to &uname;
grant UNDER ANY TYPE                     to &uname;
grant UNDER ANY VIEW                     to &uname;
grant UPDATE ANY CUBE                    to &uname;
grant UPDATE ANY CUBE BUILD PROCESS      to &uname;
grant UPDATE ANY CUBE DIMENSION          to &uname;
grant UPDATE ANY TABLE                   to &uname;
grant USE ANY JOB RESOURCE               to &uname;
grant USE ANY SQL TRANSLATION PROFILE    to &uname;